version: "3.8"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: always
    network_mode: "host"
    volumes:
      - ./conf:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
    deploy:
      resources:
        limits:
          memory: 512M
